/* AUTHENTICATION */
// Register
export const AUTH_REGISTER = "AUTH_REGISTER";
export const AUTH_REGISTER_SUCCESS = "AUTH_REGISTER_SUCCESS";
export const AUTH_REGISTER_FAILURE = "AUTH_REGISTER_FAILURE";
// Login
export const AUTH_LOGIN = "AUTH_LOGIN";
export const AUTH_LOGIN_SUCCESS = "AUTH_LOGIN_SUCCESS";
export const AUTH_LOGIN_FAILURE = "AUTH_LOGIN_FAILURE";
// Get status
export const AUTH_GET_STATUS = "AUTH_GET_STATUS";
// Logout
export const AUTH_LOGOUT = "AUTH_LOGOUT";

/* ARTICLE CRUD */
// Create
export const ARTICLE_POST = "ARTICLE_POST";
export const ARTICLE_POST_SUCCESS = "ARTICLE_POST_SUCCESS";
export const ARTICLE_POST_FAILURE = "ARTICLE_POST_FAILURE";
// Retrieve
export const ARTICLE_LIST = "ARTICLE_LIST";
export const ARTICLE_LIST_SUCCESS = "ARTICLE_LIST_SUCCESS";
export const ARTICLE_LIST_FAILURE = "ARTICLE_LIST_FAILURE";